# Generated by Django 4.1.6 on 2023-03-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_employee_facebook_employee_linkedin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="profile_pic",
        ),
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/profile_pics/"
            ),
        ),
    ]
