# Generated by Django 4.1.6 on 2023-02-17 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sale_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], default='Deb', max_length=8)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(choices=[('Pieces', 'Pieces'), ('Meters', 'Meters'), ('Boxes', 'Boxes'), ('Cartons', 'Cartons')], default='Pieces', max_length=100)),
                ('item', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProformaReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(choices=[('Pieces', 'Pieces'), ('Meters', 'Meters'), ('Boxes', 'Boxes'), ('Cartons', 'Cartons')], default='Pieces', max_length=100)),
                ('item', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(choices=[('Pieces', 'Pieces'), ('Meters', 'Meters'), ('Boxes', 'Boxes'), ('Cartons', 'Cartons')], default='Pieces', max_length=100)),
                ('item', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.FloatField(default=0)),
                ('received_by', models.CharField(max_length=255)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.employee')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=255)),
                ('received_by', models.CharField(max_length=255)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.employee')),
            ],
        ),
    ]
