# Generated by Django 4.1.6 on 2023-02-04 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_rename_userprofile_employee_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cash',
            new_name='CashReceipt',
        ),
        migrations.RenameModel(
            old_name='Invoice',
            new_name='InvoiceReceipt',
        ),
        migrations.RenameModel(
            old_name='Proforma',
            new_name='ProformaReceipt',
        ),
    ]
