# Generated by Django 4.1.6 on 2023-02-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(),
        ),
    ]
