# Generated by Django 4.1.6 on 2023-02-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_position_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceipt',
            name='sale_type',
            field=models.CharField(choices=[('Deb', 'Debit'), ('Cre', 'Credit')], default='Deb', max_length=8),
        ),
    ]
