# Generated by Django 4.1.6 on 2023-02-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_cashreceipt_sale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceipt',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
