# Generated by Django 4.1.6 on 2023-02-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_invoicereceipt_total_proformareceipt_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashreceipt',
            name='unit',
            field=models.CharField(choices=[('Pieces', 'Pieces'), ('Meters', 'Meters'), ('Boxes', 'Boxes'), ('Cartons', 'Cartons')], default='Pieces', max_length=100),
        ),
        migrations.AddField(
            model_name='invoicereceipt',
            name='unit',
            field=models.CharField(choices=[('Pieces', 'Pieces'), ('Meters', 'Meters'), ('Boxes', 'Boxes'), ('Cartons', 'Cartons')], default='Pieces', max_length=100),
        ),
        migrations.AddField(
            model_name='proformareceipt',
            name='unit',
            field=models.CharField(choices=[('Pieces', 'Pieces'), ('Meters', 'Meters'), ('Boxes', 'Boxes'), ('Cartons', 'Cartons')], default='Pieces', max_length=100),
        ),
    ]
